{% set version = "0.6.1" %}

package:
  name: vale-styles-google
  version: {{ version }}

source:
  - folder: Google
    fn: vale-Google-0.6.0.zip
    url: https://github.com/errata-ai/Google/releases/download/v{{ version }}/Google.zip
    sha256: ca77de1cc64f789f124f573847b0754be5d9e180022f6e3a51d3651fd49402af
  - fn: LICENSE-vale-Google-0.6.0
    url: https://raw.githubusercontent.com/errata-ai/Google/v{{ version }}/LICENSE
    sha256: f661986be23c000812a439e03dfed8d16ff23117e8d1219fc2beb7cd01393640

build:
  noarch: generic
  number: 0

requirements:
  host:
    - vale
  run:
    - vale

test:
  requires:
    - pytest

about:
  home: https://github.com/errata-ai/Google
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Google rules for vale grammar and style checker

extra:
  recipe-maintainers:
    - bollwyvl
