{% set version = "0.6.0" %}

package:
  name: vale-styles-google
  version: {{ version }}

source:
  - folder: Google
    fn: vale-Google-0.6.0.zip
    url: https://github.com/errata-ai/Google/releases/download/v{{ version }}/Google.zip
    sha256: 629e834b99fa58beea29bf3d81da850f3543bebe98b99731d14cf7dd72650265
  - fn: LICENSE-vale-Google-0.6.0
    url: https://raw.githubusercontent.com/errata-ai/Google/v{{ version }}/LICENSE
    sha256: f661986be23c000812a439e03dfed8d16ff23117e8d1219fc2beb7cd01393640

build:
  noarch: generic
  number: 0

requirements:
  host:
    - vale
  run:
    - vale

test:
  requires:
    - pytest

about:
  home: https://github.com/errata-ai/Google
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Google rules for vale grammar and style checker

extra:
  recipe-maintainers:
    - bollwyvl
